version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres

  redis:
    image: redis:6.2
    expose:
      - "6379"


volumes:
  postgres_data:
  postgres_backups: